export const rarityOdds = { legendary: 0.02, uncommon: 0.18, common: 0.8 };
export const collectibles = [
  { id: 1, key: "espresso_lightning_bolt", name: "Espresso Lightning Bolt", description: "Shiny espresso cup with a neon bolt through it.", rarity: "uncommon" },
  { id: 2, key: "matcha_wave", name: "Matcha Wave", description: "Huge green matcha wave curling out of a tea bowl.", rarity: "uncommon" },
  { id: 3, key: "oat_cloud", name: "Oat Cloud", description: "Fluffy cloud made entirely of oat milk foam.", rarity: "common" },
  { id: 4, key: "cocoa_comet", name: "Cocoa Comet", description: "Cocoa-colored comet with a marshmallow tail.", rarity: "uncommon" },
  { id: 5, key: "pumpkin_rocket", name: "Pumpkin Rocket", description: "Pumpkin spice latte blasting off like a rocket.", rarity: "uncommon" },
  { id: 6, key: "vanilla_star", name: "Vanilla Star", description: "Star-shaped vanilla latte glowing in the sky.", rarity: "common" },
  { id: 7, key: "brown_sugar_swirl", name: "Brown Sugar Swirl", description: "Twisted golden sugar swirl hovering above a cup.", rarity: "common" },
  { id: 8, key: "coconut_island", name: "Coconut Island", description: "Coconut latte sitting on a tiny floating tropical island.", rarity: "uncommon" },
  { id: 9, key: "cookie_butter_peak", name: "Cookie Butter Peak", description: "Mountain peak of cookie crumbs and milk foam.", rarity: "uncommon" },
  { id: 10, key: "bean_galaxy", name: "Bean Galaxy", description: "Spiral galaxy formed from hundreds of tiny coffee beans.", rarity: "legendary" },
  { id: 11, key: "foam_crown", name: "Foam Crown", description: "Royal crown made entirely from smooth milk foam.", rarity: "common" },
  { id: 12, key: "iced_avalanche", name: "Iced Avalanche", description: "Cup overflowing with tumbling ice cubes.", rarity: "common" },
  { id: 13, key: "matcha_samurai", name: "Matcha Samurai", description: "Matcha whisk wearing tiny samurai armor.", rarity: "uncommon" },
  { id: 14, key: "espresso_astronaut", name: "Espresso Astronaut", description: "Mini astronaut holding an espresso shot in space.", rarity: "uncommon" },
  { id: 15, key: "syrup_rainbow", name: "Syrup Rainbow", description: "Rainbow arc of colorful syrups pouring into a mug.", rarity: "common" },
  { id: 16, key: "bean_submarine", name: "Bean Submarine", description: "Submarine shaped like a giant coffee bean underwater.", rarity: "common" },
  { id: 17, key: "matcha_koi", name: "Matcha Koi", description: "Green koi fish swimming inside a clear teacup.", rarity: "uncommon" },
  { id: 18, key: "jolt_mini_bot", name: "JOLT Mini Bot", description: "Cute chibi vending machine with big eyes and a smile.", rarity: "common" },
  { id: 19, key: "grinder_guardian", name: "Grinder Guardian", description: "Tiny guardian spirit perched on metal grinder burrs.", rarity: "common" },
  { id: 20, key: "filter_sprite", name: "Filter Sprite", description: "Glowing paper-filter fairy sprinkling clean water.", rarity: "common" },
  { id: 21, key: "steam_phoenix", name: "Steam Phoenix", description: "Phoenix bird rising from a plume of cup steam.", rarity: "legendary" },
  { id: 22, key: "double_shot_dolphin", name: "Double Shot Dolphin", description: "Dolphin leaping through two espresso streams.", rarity: "uncommon" },
  { id: 23, key: "latte_lava_lamp", name: "Latte Lava Lamp", description: "Latte trapped inside a retro lava lamp shape.", rarity: "uncommon" },
  { id: 24, key: "mocha_thundercloud", name: "Mocha Thundercloud", description: "Storm cloud raining mocha drops and tiny lightning.", rarity: "legendary" },
  { id: 25, key: "oat_milk_unicorn", name: "Oat Milk Unicorn", description: "Unicorn with an oat-latte rainbow mane.", rarity: "uncommon" },
  { id: 26, key: "espresso_octopus", name: "Espresso Octopus", description: "Octopus juggling eight mini espresso cups.", rarity: "uncommon" },
  { id: 27, key: "matcha_ufo", name: "Matcha UFO", description: "Flying saucer beaming up a swirl of matcha powder.", rarity: "uncommon" },
  { id: 28, key: "bean_zeppelin", name: "Bean Zeppelin", description: "Airship body made from a huge roasted coffee bean.", rarity: "uncommon" },
  { id: 29, key: "sugar_castle", name: "Sugar Castle", description: "Castle towers built from stacked sugar cubes.", rarity: "common" },
  { id: 30, key: "ice_bear", name: "Ice Bear", description: "Polar bear lounging in a giant iced latte.", rarity: "common" },
  { id: 31, key: "whisk_wizard", name: "Whisk Wizard", description: "Wizard with a matcha whisk as a magic staff.", rarity: "uncommon" },
  { id: 32, key: "shot_glass_shark", name: "Shot Glass Shark", description: "Friendly shark circling inside a tiny espresso shot.", rarity: "common" },
  { id: 33, key: "latte_lightning_wolf", name: "Latte Lightning Wolf", description: "Wolf howling with lightning-shaped steam rising.", rarity: "uncommon" },
  { id: 34, key: "bean_volcano", name: "Bean Volcano", description: "Volcano erupting hot coffee instead of lava.", rarity: "legendary" },
  { id: 35, key: "matcha_surf_rider", name: "Matcha Surf Rider", description: "Character surfing a bright green matcha wave.", rarity: "uncommon" },
  { id: 36, key: "pumpkin_spice_yeti", name: "Pumpkin Spice Yeti", description: "Cozy yeti hugging a steaming pumpkin drink.", rarity: "common" },
  { id: 37, key: "coconut_surfer", name: "Coconut Surfer", description: "Coconut character riding a foam surfboard.", rarity: "common" },
  { id: 38, key: "cookie_butter_bear", name: "Cookie Butter Bear", description: "Bear holding a gooey cookie-butter latte.", rarity: "common" },
  { id: 39, key: "vanilla_aurora", name: "Vanilla Aurora", description: "Northern lights made of soft vanilla-colored steam.", rarity: "legendary" },
  { id: 40, key: "brown_sugar_dragon", name: "Brown Sugar Dragon", description: "Dragon coiled around a brown sugar latte cup.", rarity: "legendary" },
  { id: 41, key: "matcha_firefly", name: "Matcha Firefly", description: "Tiny glowing fireflies orbiting a matcha bowl.", rarity: "common" },
  { id: 42, key: "espresso_skyline", name: "Espresso Skyline", description: "City skyline built from stacked espresso cups.", rarity: "uncommon" },
  { id: 43, key: "night_shift_owl", name: "Night Shift Owl", description: "Owl with glowing coffee bean eyes on a night branch.", rarity: "uncommon" },
  { id: 44, key: "morning_lark", name: "Morning Lark", description: "Bird carrying a sunrise latte in its claws.", rarity: "common" },
  { id: 45, key: "hopper_treasure_chest", name: "Hopper Treasure Chest", description: "Powder hopper opening like a treasure chest of powder.", rarity: "common" },
  { id: 46, key: "syrup_sea_serpent", name: "Syrup Sea Serpent", description: "Playful serpent body made from looping syrup ribbons.", rarity: "uncommon" },
  { id: 47, key: "ice_crystal_fox", name: "Ice Crystal Fox", description: "Fox with an ice-crystal tail guarding a cold drink.", rarity: "uncommon" },
  { id: 48, key: "cup_stack_tower", name: "Cup Stack Tower", description: "Wobbly tower of smiling cups about to topple.", rarity: "common" },
  { id: 49, key: "bean_rocket_scooter", name: "Bean Rocket Scooter", description: "Scooter shaped like a coffee bean zooming forward.", rarity: "common" },
  { id: 50, key: "matcha_nebula", name: "Matcha Nebula", description: "Cosmic nebula of matcha dust and twinkling stars.", rarity: "legendary" },
  { id: 51, key: "sunrise_city_brew", name: "Sunrise City Brew", description: "Sun rising behind a skyline of coffee cups on the horizon.", rarity: "uncommon" },
  { id: 52, key: "midnight_metro_mocha", name: "Midnight Metro Mocha", description: "Subway train with windows glowing like latte art.", rarity: "uncommon" },
  { id: 53, key: "tokyo_neon_matcha", name: "Tokyo Neon Matcha", description: "Matcha bowl lit by neon city signs and billboards.", rarity: "legendary" },
  { id: 54, key: "paris_cafe_crescent", name: "Paris Café Crescent", description: "Croissant-shaped moon dipping into a cappuccino.", rarity: "common" },
  { id: 55, key: "brooklyn_bridge_brew", name: "Brooklyn Bridge Brew", description: "Suspension bridge with coffee flowing under it.", rarity: "uncommon" },
  { id: 56, key: "sahara_mirage_latte", name: "Sahara Mirage Latte", description: "Cup shimmering above hot desert dunes.", rarity: "common" },
  { id: 57, key: "arctic_aurora_cold_brew", name: "Arctic Aurora Cold Brew", description: "Icy glass glowing under swirling northern lights.", rarity: "legendary" },
  { id: 58, key: "jungle_canopy_cappuccino", name: "Jungle Canopy Cappuccino", description: "Vines and parrots circling a foamy cup.", rarity: "uncommon" },
  { id: 59, key: "rainforest_canopy_matcha", name: "Rainforest Canopy Matcha", description: "Thick green canopy reflected in a tea bowl.", rarity: "common" },
  { id: 60, key: "alpine_summit_espresso", name: "Alpine Summit Espresso", description: "Tiny climber planting a flag in espresso crema.", rarity: "legendary" },
  { id: 61, key: "island_hammock_iced_latte", name: "Island Hammock Iced Latte", description: "Hammock strung between two palm-tree straws.", rarity: "common" },
  { id: 62, key: "desert_dunes_latte", name: "Desert Dunes Latte", description: "Latte cup half-buried in warm spice-colored sand.", rarity: "common" },
  { id: 63, key: "volcano_island_mocha", name: "Volcano Island Mocha", description: "Volcano cone pouring molten chocolate into the sea.", rarity: "legendary" },
  { id: 64, key: "ocean_reef_refresher", name: "Ocean Reef Refresher", description: "Coral reef shapes made from ice cubes in a clear drink.", rarity: "uncommon" },
  { id: 65, key: "northern_lights_nitro", name: "Northern Lights Nitro", description: "Night-sky drink streaked with neon aurora bands.", rarity: "legendary" },
  { id: 66, key: "city_rooftop_cortado", name: "City Rooftop Cortado", description: "Rooftop garden party around a single glowing cortado.", rarity: "uncommon" },
  { id: 67, key: "gondola_macchiato", name: "Gondola Macchiato", description: "Venetian gondola carved from a tilted espresso cup.", rarity: "common" },
  { id: 68, key: "safari_sunset_brew", name: "Safari Sunset Brew", description: "Animal silhouettes against a latte-colored sunset sky.", rarity: "uncommon" },
  { id: 69, key: "temple_garden_matcha", name: "Temple Garden Matcha", description: "Stone lanterns and koi pond around a calm tea bowl.", rarity: "uncommon" },
  { id: 70, key: "castle_keep_cocoa", name: "Castle Keep Cocoa", description: "Medieval castle walls built from chocolate bricks.", rarity: "common" },
  { id: 71, key: "pirate_ship_cold_brew", name: "Pirate Ship Cold Brew", description: "Pirate ship with sails woven from coffee steam.", rarity: "uncommon" },
  { id: 72, key: "meteor_shower_americano", name: "Meteor Shower Americano", description: "Dark-sky drink raining bright meteor streaks.", rarity: "uncommon" },
  { id: 73, key: "galaxy_rail_latte", name: "Galaxy Rail Latte", description: "Train riding the rings of a giant coffee planet.", rarity: "uncommon" },
  { id: 74, key: "coral_lagoon_latte", name: "Coral Lagoon Latte", description: "Shallow tropical bay scene inside a blended drink.", rarity: "uncommon" },
  { id: 75, key: "oasis_palm_espresso", name: "Oasis Palm Espresso", description: "Tiny palm oasis reflected in a demitasse.", rarity: "common" },
  { id: 76, key: "bamboo_grove_matcha", name: "Bamboo Grove Matcha", description: "Tall bamboo stalks framing a glowing green bowl.", rarity: "uncommon" },
  { id: 77, key: "savannah_sunrise_chai", name: "Savannah Sunrise Chai", description: "Warm orange chai over savannah grass silhouettes.", rarity: "common" },
  { id: 78, key: "glacier_drift_cold_brew", name: "Glacier Drift Cold Brew", description: "Icebergs floating in a deep inky cold brew.", rarity: "legendary" },
  { id: 79, key: "orchard_harvest_latte", name: "Orchard Harvest Latte", description: "Apple and pear trees leaning toward a warm cup.", rarity: "common" },
  { id: 80, key: "lantern_festival_matcha", name: "Lantern Festival Matcha", description: "Floating lanterns mirrored in still green tea.", rarity: "uncommon" },
  { id: 81, key: "rainy_day_window_brew", name: "Rainy Day Window Brew", description: "City window with raindrops and a cozy mug on the sill.", rarity: "common" },
  { id: 82, key: "cloud_city_cappuccino", name: "Cloud City Cappuccino", description: "Floating foam islands with tiny buildings on top.", rarity: "uncommon" },
  { id: 83, key: "jungle_waterfall_iced_matcha", name: "Jungle Waterfall Iced Matcha", description: "Waterfall pouring into a tall green drink.", rarity: "uncommon" },
  { id: 84, key: "market_street_espresso", name: "Market Street Espresso", description: "Blurred busy street behind a sharp espresso shot.", rarity: "common" },
  { id: 85, key: "starport_latte_dock", name: "Starport Latte Dock", description: "Space station ring with cups docked all around.", rarity: "uncommon" },
  { id: 86, key: "lighthouse_macchiato", name: "Lighthouse Macchiato", description: "Lighthouse beam shining from a foamy macchiato top.", rarity: "common" },
  { id: 87, key: "coral_bay_frappe", name: "Coral Bay Frappé", description: "Shallow tropical bay scene inside a blended drink.", rarity: "common" },
  { id: 88, key: "mango_monsoon_matcha", name: "Mango Monsoon Matcha", description: "Storm of mango cubes swirling through green tea.", rarity: "legendary" },
  { id: 89, key: "cherry_blossom_brew", name: "Cherry Blossom Brew", description: "Pink petals drifting onto a soft latte surface.", rarity: "uncommon" },
  { id: 90, key: "time_travelers_espresso", name: "Time Traveler's Espresso", description: "Pocket watch swirling inside an espresso spiral.", rarity: "legendary" },
  { id: 91, key: "skyline_rainbow_refresher", name: "Skyline Rainbow Refresher", description: "Stacked city skylines in layered drink colors.", rarity: "uncommon" },
  { id: 92, key: "forest_cabin_cocoa", name: "Forest Cabin Cocoa", description: "Snowy cabin lit by a steaming mug in the window.", rarity: "common" },
  { id: 93, key: "meteor_crater_cortado", name: "Meteor Crater Cortado", description: "Tiny impact crater that looks like crema art.", rarity: "uncommon" },
  { id: 94, key: "lunar_eclipse_latte", name: "Lunar Eclipse Latte", description: "Half-shadowed foam ring like an eclipse.", rarity: "uncommon" },
  { id: 95, key: "pegasus_cloud_cold_foam", name: "Pegasus Cloud Cold Foam", description: "Winged horse racing along cold foam clouds.", rarity: "uncommon" },
  { id: 96, key: "coral_compass_cold_brew", name: "Coral Compass Cold Brew", description: "Old compass resting at the bottom of a clear drink.", rarity: "common" },
  { id: 97, key: "sandcastle_iced_coffee", name: "Sandcastle Iced Coffee", description: "Sandcastle walls built around a plastic cup.", rarity: "common" },
  { id: 98, key: "floating_market_matcha", name: "Floating Market Matcha", description: "Little boats clustered around a central tea bowl.", rarity: "uncommon" },
  { id: 99, key: "sunken_treasure_tonic", name: "Sunken Treasure Tonic", description: "Sparkling drink with coins and gems at the base.", rarity: "common" },
  { id: 100, key: "world_tour_flight_tray", name: "World Tour Flight Tray", description: "Row of tiny cups, each wrapped in a different flag.", rarity: "uncommon" }
];
